name: 'Jest Coverage Comment Action'
description: 'Comments a PR with the coverage (jest)'
author: raulanatol
branding:
  color: green
  icon: message-circle
inputs:
  github-token:
    description: 'Github token'
    required: true
  jest-command:
    description: 'The jest command'
    required: false
    default: 'npx jest --coverage'
  only-changes:
    description: 'Add parameter to show the coverage only for the changed files'
    required: false
    default: 'true'
  working-directory:
    description: 'Specify a directory where npm command has to be executed'
    required: false
    default: ''
  delete-previous:
    description: 'Delete previous comments before adding a new one'
    required: false
    default: 'true'
runs:
  using: 'node12'
  main: 'dist/index.js'
